name: Test Pipeline with Inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'test message'
        required: true
        default: 'default message test'
      test1:
        description: 'test1 desc'
        required: false
        default: 'test1'

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "message: ${{ github.event.inputs.message }}"
          echo "params: ${{ github.event.inputs.test1 }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p build && echo "Hello World" > build/hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/

  build2:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p build2 && echo "Hello World2" > build/hello2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build2/
